f = open('245.txt') 
s = f.readline()
s = s.replace('BWI','1')
s = s.replace('OKM','*')
s = s.replace('OK','*')
s = s.replace('CP','*')
s = s.replace('PP','*')
k = s.count('1')
sum = len(s)
z = k - int(0.2*sum)
print(z)
